### ISSUE TITLE
Security contact?

### ISSUE THREAD

**Issue by JarLob** [MatthewKing/IdentityWithoutEF#5]
Hi, how could I report a potential security vulnerability in the project?

**Comment by MatthewKing** [comment]
You can report it via a PR, or in this issue.

Just to be clear, though - this isn't a production project, it's just a (very old) example targeting an outdated version of ASP.NET Core. There are obviously security issues with the outdated Microsoft.AspNetCore.All / Microsoft.AspNetCore.Mvc / Microsoft.AspNetCore.Identity dependencies, but that is out of scope for this example project.

Cheers
